name: Unit Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: '>=3.6 <3.11'
          cache: 'pip'

    - name: Install dependencies
      run: pip install smbus2

    - name: Run unit tests
      run: python -m unittest test.py